services:
  # Backend API Service
  - type: web
    name: breast-cancer-api
    env: docker
    dockerfilePath: ./api/Dockerfile
    dockerContext: ./api
    healthCheckPath: /predict
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: PYTHONUNBUFFERED
        value: "1"

  # Frontend Service
  - type: web
    name: breast-cancer-ui
    env: static
    buildCommand: cd breast-cancer-ui && npm install && npm run build
    staticPublishPath: breast-cancer-ui/out
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_API_URL
        value: https://breast-cancer-api-74zl.onrender.com/predict 